# Generated by Django 2.2.3 on 2019-07-21 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('no_of_members', models.PositiveIntegerField()),
                ('savings', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('begin_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('searchable', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
