# Generated by Django 2.2.3 on 2019-07-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190722_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='created_by',
        ),
    ]
