# Generated by Django 2.2.3 on 2019-07-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groups_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
